### ISSUE TITLE
add my git course

### ISSUE THREAD

**Issue by shahriaarrr** [ahmadalibagheri/devops-roadmap#5]
Hi. I posted a git course on my YouTube channel that almost explained the basics and main points of the git. If the quality of the course was good, I would be happy for you to put the link in this repository.
@ahmadalibagheri 

[**my git course**](https://www.youtube.com/playlist?list=PLNjdjZpVESU47wGkPh2U-UoWc9382dNG2)

**Comment by ahmadalibagheri** [comment]
Thank you @shahriaarrr ok sure i will assign to some guys to check your content.  

@babakDoraniArab @rojinebrahimi @Mozart4242 @bobycloud  Please check this content. If it's useful for DevOps joiners, please approve that to add to our Roadmap.

**Comment by babakDoraniArab** [comment]
> my git course

I've checked the course. it would be good to start with this course if the trainee is a junior, but I think Mosh explained this topic in more depth

**Comment by Mozart4242** [comment]
I checked it, too, and the parts are a bit long with not well explained topics.
I would definitely go with mosh (for english) and Jadi (for farsi).

**Comment by shahriaarrr** [comment]
Thanks to @babakDoraniArab  and  @Mozart4242  for reviewing this course🙏🙏
As I explained above, in this course I explained most of the basics and useful git commands. This course is going to be updated and newer topics will be added for it. You can see in the course, or things in the course that have not been taught or poorly explained, you can explain to me here so that I can make corrections in this course❤️

**Comment by babakDoraniArab** [comment]
> Thanks to @babakDoraniArab and @Mozart4242 for reviewing this course🙏🙏 As I explained above, in this course I explained most of the basics and useful git commands. This course is going to be updated and newer topics will be added for it. You can see in the course, or things in the course that have not been taught or poorly explained, you can explain to me here so that I can make corrections in this course❤️

@shahriaarrr 
sounds great. please update the course and keep us posted. I think you can make a good resource for the git with some small projects and go more in depth of the topics.

**Comment by rojinebrahimi** [comment]
Hey! I had a look at the course contents and I found it decent to kickstart Git as a beginner, but I believe it could be improved by using more complex examples. Keep up!

**Comment by BobbyBabazadeh** [comment]
+1 needs improvement; keep up the good work. The devil is in the details.

**Comment by babakDoraniArab** [comment]
we will be talking more about the new version
