### ISSUE TITLE
Please add hamed terraform course

### ISSUE THREAD

**Issue by MParvin** [ahmadalibagheri/devops-roadmap#9]
Ahmad jan
Please add Hamde farvardin terraform course:

https://linux.tosinso.com/fa/videos/10492/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%AA%D8%B1%D8%A7%D9%81%D8%B1%D9%85-(Terraform)-%D9%82%D8%B3%D9%85%D8%AA-1-%D9%85%D8%B9%D8%B1%D9%81%DB%8C-%D8%AA%D8%B1%D8%A7%D9%81%D9%88%D8%B1%D9%85

**Comment by ahmadalibagheri** [comment]
I'm happy to add. you can create PR and i will approve that.

**Comment by MParvin** [comment]
Thank you, I've added it in #10

**Comment by ahmadalibagheri** [comment]
Thank you so much.
